WindowsMain:
  title: '是弹幕姬吧'
  icon: 'image\Hbicon.ico'
  background: 'image\MainBg.png'

menu:
  # font:'微软雅黑'
    # family: 
    # size: 14
    # color: '#FFFFFF'
    # background: '#000000'
    # hover_color: '#FF0000'
    # hover_background: '#FFFFFF'
    # active_color: '#0000FF'
    # active_background: '#00FF00'


  optionList: 
    0: "介绍"
    1: "功能"
    2: "设置"
    # 3: "test3"
    # 4: "test4"
    # 5: "test5"
    # 6: "test6"
    # 7: "test7"
    # 8: "test8"
    # 9: "test9"
    
    