# Form implementation generated from reading ui file 'F:\Hammahime\UI\WindowsMainGUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 469)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(817, 469))
        self.centralwidget.setMaximumSize(QtCore.QSize(817, 469))
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 771, 61))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.toolButton_2 = QtWidgets.QToolButton(parent=self.groupBox)
        self.toolButton_2.setGeometry(QtCore.QRect(10, 10, 141, 40))
        self.toolButton_2.setMinimumSize(QtCore.QSize(141, 40))
        self.toolButton_2.setMaximumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("F:\\Hammahime\\UI\\../image/Hbicon.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setIconSize(QtCore.QSize(32, 32))
        self.toolButton_2.setAutoRepeat(False)
        self.toolButton_2.setAutoExclusive(False)
        self.toolButton_2.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.toolButton_2.setObjectName("toolButton_2")
        self.listView = QtWidgets.QListView(parent=self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(0, 0, 821, 471))
        self.listView.setMinimumSize(QtCore.QSize(821, 471))
        self.listView.setMaximumSize(QtCore.QSize(821, 471))
        self.listView.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.listView.setAutoFillBackground(False)
        self.listView.setStyleSheet("background-image: url(:/MainBg.png)")
        self.listView.setObjectName("listView")
        self.listView_2 = QtWidgets.QListView(parent=self.centralwidget)
        self.listView_2.setGeometry(QtCore.QRect(0, 0, 821, 471))
        self.listView_2.setMinimumSize(QtCore.QSize(821, 471))
        self.listView_2.setMaximumSize(QtCore.QSize(821, 471))
        self.listView_2.setStyleSheet("background-color: rgba(0, 0, 0, .3);")
        self.listView_2.setObjectName("listView_2")
        self.listView.raise_()
        self.listView_2.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionxinjian = QtGui.QAction(parent=MainWindow)
        self.actionxinjian.setObjectName("actionxinjian")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton_2.setText(_translate("MainWindow", "关于"))
        self.actionxinjian.setText(_translate("MainWindow", "xinjian"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
